version: 2

buildSteps: &buildSteps
  - setup_remote_docker
  - checkout
  - run:
      name: install-npm
      command: npm i
  - run:
      name: test
      command: npm test

jobs:
  'node-8':
    docker:
      - image: circleci/node:8
    working_directory: ~/node-8
    steps: *buildSteps

  'node-10':
    docker:
      - image: circleci/node:10
    working_directory: ~/node-10
    steps: *buildSteps

  'node-12':
    docker:
      - image: circleci/node:12
    working_directory: ~/node-12
    steps: *buildSteps

workflows:
  version: 2
  build:
    jobs:
      - 'node-8'
      - 'node-10'
      - 'node-12'
